# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d86e5a0d8021f98a1d6f9b498e7f377f35e1ef8cbe5db20b43d752d68b1597a5b75191962e21e42f7273b20958b39444a6bcc553a25bacbf12dfcac1a33187dd
  telegram:
    bot: <%= ENV["TELEGRAM_TOKEN"] %>
test:
  secret_key_base: 7a5f2687b0f72b58adfe723c20369d8e1d6abcc03078c2f68a29404d8c6a44f23aa3f09023ff9312c9e6e20189fe34b00559e38e2f958c8638a97f652ce9318c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  telegram:
    bot: <%= ENV["TELEGRAM_TOKEN"] %>
